# Promtail configuration with Docker service discovery
# SPDX-License-Identifier: PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni DAO

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # basic_auth:
    #   username: <user>
    #   password: <pass>
    # OR: tenant_id: <tenant>

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
        regex: "/(.*)"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "compose_service"
        regex: "(.*)"
        replacement: "${1}"
      - source_labels:
          ["__meta_docker_container_label_io_kubernetes_container_name"]
        target_label: "k8s_container" # harmless if absent
      - source_labels: ["__meta_docker_container_label_maintainer"]
        target_label: "maintainer"
    pipeline_stages:
      - docker: {} # parses docker JSON log line into labels/message
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          container:
          compose_service:
          stream:
